babylonlabs-io/simple-staking

src/app/components/Delegations/Delegations.tsx
src/app/components/Staking/Staking.tsx

When trying to add an item to local storage delegations (staking) or intermediate local storage delegations (unbonding, withdrawing) using multiple Chrome extension wallet windows, we will end up add multiple items.
This PR solves it. If the item is already present in the local storage - we don't do anything.
@jeremy-babylonlabs @jrwbabylonlab when trying to "double/triple unbond", we will see this error message: https://i.imgur.com/JvtuGWp.png. Not sure if it's "good enough" for the end user.
Problems with the current PR implementation - theoretically our local storage methods `setDelegationsLocalStorage` and `setIntermediateDelegationsLocalStorage` do almost identical stuff. Should we combine them? If so - when?
- This PR contains code duplication, which is a "smell"
- "Proper" solution …

fix: Local storage no duplicate

---

.github/workflows/ci.yml
.github/workflows/publish.yaml
src/app/components/Modals/ErrorModal.tsx
src/app/components/Staking/Staking.tsx
src/app/context/Error/ErrorContext.tsx
src/app/page.tsx
src/app/types/errors.ts

After you try to stake and some error happens, you can "Try again". Modal is closed, UTXOs are refetched.
Video recorded with the cancel button, then removed it. Only "try again" is available: https://youtu.be/-zcJTXIXqng
"No cancel" video: https://youtu.be/ETjAXdqkegE
Closes #63

fix: Refetch UTXOs on unsuccessful staking

---

package-lock.json
package.json
src/app/components/Staking/FinalityProviders/FinalityProviders.tsx
src/app/components/Staking/Form/StakingAmount.tsx
src/app/components/Staking/Staking.tsx

Hotfix - clean input after staking and updated title text

---

package-lock.json
package.json
src/app/components/Modals/PreviewModal.tsx
src/app/components/Staking/Staking.tsx

Result https://i.imgur.com/nF4oKis.png
- adds unbonding fee to the:
- text
- grid

feature: Preview Unbonding fee

---

package-lock.json
package.json
src/app/components/Modals/ConnectModal.tsx

cleans out the checkbox after the connection

fix: Clean out "No HW wallet checkbox" after connection

---

src/app/components/Delegations/Delegations.tsx
src/app/components/Modals/ErrorModal.tsx
src/app/components/Stakers/Stakers.tsx
src/app/components/Staking/Staking.tsx
src/app/context/Error/ErrorContext.tsx
src/app/context/api/StakingStatsProvider.tsx
src/app/hooks/useHealthCheck.ts
src/app/page.tsx
src/app/types/errors.ts

feat: remove error timestamp

---

src/app/components/Delegations/Delegations.tsx
src/app/components/Loading/Loading.tsx
src/app/components/Modals/GeneralModal.tsx
src/app/components/Modals/PreviewModal.tsx
src/app/components/Modals/UnbondWithdrawModal.tsx
src/app/components/Staking/Staking.tsx

Adds loading state while signing the TX.
Problematic part - https://github.com/pradel/react-responsive-modal/issues/504
Currently, react-responsive-modal cannot dynamically update the `ESC` button behavior. I.e. we cannot **_easily_**:
- create a modal
- add a support fort this modal to be closed via the `ESC` button (default behavior)
- then disable the `ESC` key because our prop changed
So PreviewModal is not closable via `ESC` by default
In terms of our general approach. Since per design we don't have to differentiate between `wallet is signing` and `wallet is broadcasting to the blockchain` the whole "disabling" process will be enabled until the whole `signing + broadcasting` finishes. It is reset though once closed or error happens. For example, if we reject from the mobile
Video: …

feature: Modal loading while staking

---

package-lock.json
package.json
src/app/components/Delegations/Delegations.tsx
src/app/components/Modals/UnbondWithdrawModal.tsx

This PR is a hotfix for the unbonding modal. It now displays the correct info according to the delegation height.

use correct height for unbonding model

---

package-lock.json
package.json
src/app/components/Points/DelegationPoints.tsx
src/app/components/Points/StakerPoints.tsx

fix na inconsistent display

---

src/app/components/Connect/ConnectSmall.tsx
src/app/components/Connect/ConnectedSmall.tsx
src/app/components/Header/Header.tsx
src/app/components/Modals/ConnectModal.tsx
src/app/components/Modals/FilterOrdinalsModal.tsx
src/app/page.tsx

Adds a modal and settings option to filter out ordinals
Closes #207

feature: Ordinals filtering modal

---

src/app/api/postLogTermAcceptance.ts
src/app/api/postTerms.ts
src/app/components/Modals/ErrorModal.tsx
src/app/components/Points/StakerPoints.tsx
src/app/hooks/useAcceptTerms.ts
src/app/page.tsx
src/app/types/errors.ts

connect terms-acceptance post endpoint
doesnt post again if `termsAcceptedLocalStorage` is true

feat: terms acceptance

---

src/app/components/Modals/EOIModal.tsx
src/app/components/Staking/Staking.tsx

feat(phase-2): EOI modal

---

src/app/components/Modals/PreviewModal.tsx
src/app/components/Staking/Staking.tsx

Update Preview Modal according to new [requirements](https://babylonlabs.atlassian.net/wiki/spaces/BABYLON/pages/41877853/Phase-2+UI+Components#4.3-Staking-Preview)

feat(phase-2): update preview modal

---

src/app/components/Modals/PendingVerificationModal.tsx
src/app/page.tsx

Addition of Pending Verification modal with the current design
To use it:
```tsx
const [pendingVerificationOpen, setPendingVerificationOpen] = useState(false);
const [verified, setVerified] = useState(false);
const [awaitingWalletResponse, setAwaitingWalletResponse] = useState(false);
const handlePendingOpen = async () => {
// open the modal
setPendingVerificationOpen(true);
await new Promise((resolve) => setTimeout(resolve, 3000)); // simulate waiting for BBN verification
setVerified(true);
};
const handlePendingClose = () => {
// clean out the state
setVerified(false);
setAwaitingWalletResponse(false);
setPendingVerificationOpen(false);
};
const handleStakeSignBroadcast = async () => {
console.log("start staking");
setAwaitingWalletResponse(true); // waiting for wallet response
await …
```

feature: Pending verification modal

---

package-lock.json
package.json
src/app/components/UnbondingDisabledBanner/UnbondingDisabledBanner.tsx

add missed space from annoucement

add annoucement missing space

---

src/app/components/Error/GenericError.tsx

We only have one route in the app so it makes more sense to refresh instead of navigate to the same page again.

refresh page in GenericError

---

package-lock.json
package.json
src/app/components/Staking/FinalityProviders/FinalityProviderSearch.tsx

this pr fixes the issue where `/?fp=xxx` filter is not properly applied on the list

fix search not applied on production environment

---

.github/workflows/publish.yaml
package-lock.json
package.json
src/app/components/Staking/FinalityProviders/FinalityProviderSearch.tsx
src/app/components/Staking/FinalityProviders/FinalityProviders.tsx
src/app/hooks/finalityProviders/useFinalityProvidersData.ts

fix search param handling

---

src/app/components/Delegations/Delegation.tsx
src/app/components/Delegations/DelegationActions.tsx
src/app/components/Delegations/Delegations.tsx
src/app/components/Delegations/components/DelegationCell.tsx
src/app/components/Delegations/components/DelegationStatus.tsx
src/app/components/Delegations/components/OverflowBadge.tsx
src/app/components/Modals/UnbondModal.tsx
src/components/delegations/DelegationList/components/DelegationModal.tsx

did some refactoring along the way to clean it up
button looks abit different from original design, will need to fix the core-ui for this. but this shouldn't block the merge

add phase 1 unbond button and hook up modal

---

package-lock.json
package.json
src/app/components/PersonalBalance/PersonalBalance.tsx
src/app/context/tomo/BBNConnector.tsx
src/app/context/tomo/BTCConnector.tsx
src/app/context/wallet/BTCWalletProvider.tsx
src/app/context/wallet/CosmosWalletProvider.tsx
src/app/hooks/services/useTransactionService.ts
src/utils/mempool_api.ts
src/utils/wallet/btc_wallet_provider.ts

- Bump wallet connect after all the minimization (BTC and BBN side)
- Adjust Tomo according to the new interfaces
@jrwbabylonlab @totraev please check out so I don't miss anything

feat: Bump wallet connect

---

src/config/network/bbn/testnet.ts

- Updates RPC and LCD links
- Changes the name of the variables. Before that `testnet` file had `devnet` naming (`BBN_DEVNET_RPC_URL`). Not it uses `testnet` naming (`BBN_TESTNET_RPC_URL`)

feat: Update Testnet RPC LCD

---

src/config/network/btc.ts

This PR introduces such network combos based on the env variable:
- mainnet
- btc mainnet
- bbn testnet
- testnet
- btc signet
- bbn testnet
- signet
- btc signet
- bbn devnet
@jeremy-babylonlabs @jrwbabylonlab @totraev @hiepmai-babylonchain 
question, do we want to change `BBN` signet config from
```ts
const signetConfig: BBNConfig = {
chainId: bbnDevnet.chainId,
rpc: bbnDevnet.rpc,
chainData: bbnDevnet,
networkName: "Testnet BABY",
networkFullName: "Testnet Babylon Chain",
coinSymbol: "tBABY",
};
```
to
```ts
const signetConfig: BBNConfig = {
chainId: bbnDevnet.chainId,
rpc: bbnDevnet.rpc,
chainData: bbnDevnet,
networkName: "Devnet BABY",
networkFullName: "Devnet Babylon Chain",
coinSymbol: "dBABY",
};
```
So it's visible for the user (and us) that `devnet` chain is used. Because right …

feat: Testnet env

---

src/app/components/Delegations/Delegation.tsx
src/app/hooks/services/useRegistrationService.ts
src/app/state/DelegationState.tsx
src/app/state/DelegationV2State.tsx

This is to fix the issue where we already registered the delegation to phase-2, but still showing as active in phase-1. 
The API already updated the state to something transitioned when it show up in phase-2. So by refetching the API, we essentially will hide the phase-1 old delegation

fix: refetch v1 delegations after register to phase-2

---

src/components/delegations/DelegationList/components/SlashingContent.tsx
src/components/delegations/DelegationList/components/Status.tsx
src/utils/delegations/slashing.ts

Show Invalid status and corresponding tooltip when EOI delegations are slashed

Fix slashing tooltip

---

src/app/components/Staking/FinalityProviders/FinalityProviderFilter.tsx
src/app/components/Staking/FinalityProviders/FinalityProviderSearch.tsx
src/app/components/Staking/FinalityProviders/FinalityProviderTable.tsx
src/app/providers.tsx
src/app/state/FinalityProviderState.tsx

https://github.com/user-attachments/assets/1eeb1a67-467a-4a2a-b027-f53497796374

improve fp search to allow search to not scope to showing tab

---

src/app/hooks/services/useDelegationService.ts
src/app/state/FinalityProviderState.tsx
src/components/common/Hint/index.tsx
src/components/delegations/DelegationList/components/ActionButton.tsx
src/components/delegations/DelegationList/index.tsx

disable stake when eoi fp is slashed

---

src/app/components/Modals/AddressValidationModal.tsx
src/app/hooks/useAddressValidation.ts
src/app/page.tsx
src/utils/wallet/index.ts

Closes: https://github.com/babylonlabs-io/simple-staking/issues/571

feat: validate address & pk

---

docker/Dockerfile

This might be the reason why it didn't fire anything in https://btcstaking.phase-2-devnet.babylonlabs.io/

add missing sentry config to docker image

---

src/app/hooks/services/useDelegationService.ts
src/components/delegations/DelegationList/components/SlashingContent.tsx
src/components/delegations/DelegationList/components/Status.tsx
src/components/delegations/DelegationList/index.tsx

this PR makes sure withdrawable delegations with slashed FP should always be withdrawable
also added the withdraw button on slashed state

fix withdrawable delegation

---

src/app/api/logTermAcceptance.ts
src/app/api/verifyBTCAddress.ts
src/app/context/Error/ErrorProvider.tsx

Okay, I did a dirty trick. We don't throw an error for address screening and don't delegate it to simple staking. Instead we simple display our default error modal which is generic enough

fix: address screening error

---

src/app/context/Error/ErrorProvider.tsx
tests/context/Error/ErrorProvider.test.tsx

The error keys should be put tag instead of extras in order to do proper alerts and filtering

update sentry tag

---

src/app/components/PersonalBalance/PersonalBalance.tsx
src/app/hooks/services/useRewardsService.ts
src/app/state/RewardState.tsx

Resolves the issue where BABY Balance displays as zero immediately after claiming rewards. Implemented polling mechanism that checks for balance updates for up to 20 seconds after a successful claim transaction, providing a better user experience with accurate balance information.
https://github.com/user-attachments/assets/f5409436-80e6-4f50-b43c-464c783c1b78

fix: set up polling after claiming rewards

---

sentry.client.config.ts

Every low level error (from `btc-staking-ts` or `wallet-connector`) should be wrapped into domain error (ClientError). No need group errors by low level errors and make them more prioritized then `domain` errors.

fix: exclude cause errors from sentry fingerprint

---

package-lock.json
package.json

Bumps `btc-staking-ts` and `wallet-connector` to start receiving `signPsbt` contracts

chore: bump btc-staking-ts and wallet-connector

---

e2e/fixtures/form.selectors.ts
e2e/fixtures/form.ts
e2e/fixtures/index.ts
e2e/specs/featureFlag.spec.ts

This ensures that when configures FF_MULTISTAKING=false, users will see the correct staking interface and not accidentally see the multistaking interface

feat: add feature flags component tests

---

src/ui/common/components/Multistaking/MultistakingForm/StakingFeesSection.tsx

This fixes an endless loop that caused rerenders and a crash on the UI
The finality provider object was unstable, which caused the useEffect to be rerun endlessly. We now serialise and useMemo to make the finality provider object stable.

fix: stable reference on staking fees section

---

src/ui/common/components/Activity/components/StakeExpansionSection.tsx
src/ui/common/components/ExpansionHistory/ExpansionHistoryModal.tsx
src/ui/common/hooks/services/useExpansionHistoryService.ts
src/ui/common/hooks/useExpansionHistoryModalData.ts
src/ui/common/utils/delegationTransformers.tsx

Adds an MVP history of staking expansion
- count
- modal
- linked caching for the expansions and og staking transactions
Closes #1329

feat: expansion history

---

src/ui/common/components/Multistaking/FinalityProviderField/FinalityProviderModal.tsx
src/ui/common/components/Multistaking/MultistakingForm/MultistakingFormContent.tsx
src/ui/common/components/Multistaking/MultistakingForm/UnavailableWarning.tsx
src/ui/common/hooks/useStakingExpansionAllowList.ts

This pull request updates how the "Multi-Staking Unavailable" warning is displayed and where it appears in the UI. The warning is now shown inside the `FinalityProviderModal` instead of the main multistaking form

feat: integrate UnavailableWarning component into FinalityProviderModal

---

src/ui/common/components/StakingExpansion/StakingExpansionModal.tsx
src/ui/common/errors/codes.ts
src/ui/common/hooks/services/useStakingExpansionService.ts

- shows client error in the UI using modal
- this is useful when we have errors for fee calculation
- before this implementation it was silently using the `logger`, which is not a good UX
UI:

feat: expansion error catch

---

src/ui/common/components/Activity/components/ExpansionButton.tsx
src/ui/common/components/Activity/components/StakeExpansionSection.tsx

- after we polish the app, we completely remove the `history` button when there's no expansion history
- but after we had some conversations in Figma, the decision is to `show` this button in `disabled` state
- I removed `0` so it's less distracting
UI:

feat: show disabled history, remove 0

---

src/ui/common/state/MultistakingState.tsx
tests/state/MultistakingState.test.ts

This pull request makes a small adjustment to the validation logic in the `MultistakingState` component to correctly check for the presence of the Babylon Finality Provider.
* Updated the validation in `MultistakingState` to check if `BBN_CHAIN_ID` is a key in the original value object, rather than checking if it's included in an array.

fix: add finality provider validation

---

src/ui/common/hooks/services/useStakingExpansionService.ts
src/ui/common/state/StakingExpansionTypes.ts

- better types for expansion
- remove of `any`
Closes https://github.com/babylonlabs-io/simple-staking/issues/1480

feat: expansion types

---

src/ui/common/components/Multistaking/FinalityProviderField/FinalityProviders.tsx
src/ui/common/components/Multistaking/FinalityProviders/FinalityProviderFilter.tsx
src/ui/common/components/Multistaking/FinalityProviders/FinalityProviderSearch.tsx
src/ui/common/components/Multistaking/FinalityProviders/FinalityProviderTable.tsx

To keep the design consistent, I've used the default "selected" indicator. I can use the plus icon like in the Figma if necessary.
https://github.com/user-attachments/assets/966b333a-dc5a-43eb-b816-339ba13a1358

feat: add table view for finality provider selection (#1402)

---

src/ui/common/hooks/client/api/useOrdinals.ts
src/ui/common/hooks/client/api/useSystemStats.ts
src/ui/common/hooks/client/useClient.ts

- Since `useOrdinals` is not throwing, it's logging the error manually.
- Checking the `queryKey` to understand if an error is critical in `useClient.ts`
resolves #1022

fix: prevent error modal for non critical errors

---

src/ui/baby/hooks/api/useEpochPolling.ts

Do not clear pending operations on epoch change.
Prevents pending entries disappearing after one minute.

stop clearing pending operations on epoch change to prevent disappearing unbond state

---

src/ui/common/components/Stats/Stats.tsx

phase 3:
phase 2:
Closes: #1291

feat: add tooltip to apr stats depending on phase #1291

---

src/ui/common/hooks/useExpansionHistoryModalData.ts

- reverses the order of expansion history
- before it was - `original -> staking 1 -> staking 2`
- now it is `staking 2 -> staking 1 -> original`, from recent ones to the older ones
Closes this: https://github.com/babylonlabs-io/simple-staking/issues/1526

feat: expansion history reversed

---

src/ui/common/components/Activity/components/ActivityList.tsx
src/ui/common/components/Stats/Stats.tsx
src/ui/common/hooks/services/useActivityCardTransformation.ts
src/ui/common/hooks/services/useActivityDelegations.ts
src/ui/common/hooks/services/useActivityValidation.ts
src/ui/common/hooks/services/useExpansionVisibilityService.ts
src/ui/common/utils/stakingExpansionValidation.ts

- solves the activity tab problem for exansion
- split the logic in activity list
- formats the `src/ui/common/components/Stats/Stats.tsx` because of `npm run format:fix`
Closes https://github.com/babylonlabs-io/simple-staking/issues/1532

feat: expansion activity
