- package-lock.json
- package.json
- src/app/components/FAQ/data/questions.ts
- src/app/components/Modals/ErrorModal.tsx
- unbind, unbound -> unbond
- Safe -> safe
> fix: Typos

- package-lock.json
- package.json
- src/app/components/Modals/ConnectModal.tsx
Cleans up the state on wallet connect:
- selected wallet
- terms checkbox
- inscription checkbox
> feature: Connect modal cleanup the state

- package-lock.json
- package.json
- src/app/components/Summary/Summary.tsx
- src/app/page.tsx
Remove address from `Summary` completely
> feature: Address copy

- src/app/components/Modals/FeedbackModal.tsx
Remove network name on `Feedback`
> fix: Feedback typo

- .github/workflows/sync_pr_dev_to_main.yml
- src/app/components/Summary/Summary.tsx
- src/app/globals.css
> feature: tooltip explain staked confirmation update

- src/app/components/Modals/Terms/data/terms.tsx
- src/app/layout.tsx
- src/config/index.ts
- src/config/network.config.ts
- Layout OG image uses network config instead of predefined link
- Same with Terms
> fix: App URL

- package-lock.json
- package.json
- src/app/components/Staking/FinalityProviders/FinalityProviders.tsx
- src/app/components/Staking/Staking.tsx
Staking will be activated once BTC block height **reaches**
> feature: Reach block

- package-lock.json
- package.json
- src/app/components/Modals/ConnectModal.tsx
Since we added `policy`, our first checkbox is wider than the third one: https://i.imgur.com/xmzXa1U.png. Looks bad
Changed the max width constraint: https://i.imgur.com/8b3uT4z.png
> feature: Adjust HW checkbox width

- package-lock.json
- package.json
- src/app/components/Footer/Footer.tsx
Adds a "Privacy Policy" footer link https://i.imgur.com/tc0C3LA.png
> feature: Privacy Policy footer link

- src/app/api/getPoints.ts
- src/app/context/api/DelegationsPointsProvider.tsx
fix total points show 0 by fixing up the getPoint interface and return
> fix total points show 0

- package-lock.json
- package.json
Fixes https://github.com/babylonlabs-io/simple-staking/security/dependabot/7
> bump next version

- src/app/components/Connect/ConnectSmall.tsx
- src/app/components/Connect/ConnectedSmall.tsx
- src/app/components/Header/Header.tsx
- src/app/components/Staking/Staking.tsx
- src/app/components/Summary/Summary.tsx
- src/app/page.tsx
- src/utils/delegations/signWithdrawalTx.ts
- src/utils/local_storage/filterDelegationsLocalStorage.ts
- src/utils/mempool_api.ts
> fix: mempool endpoints errors should provide better UX

- src/app/components/Delegations/Delegations.tsx
- src/app/components/Header/Header.tsx
- src/app/components/Modals/ConnectModal.tsx
- src/app/components/Staking/Form/States/WalletNotConnected.tsx
- src/app/components/Staking/Staking.tsx
- src/app/context/Error/ErrorContext.tsx
- src/app/context/wallet/WalletProvider.tsx
- src/app/page.tsx
- src/app/providers.tsx
> feat: move wallet provider logic in react context

- package-lock.json
- package.json
- src/app/components/Points/DelegationPoints.tsx
- src/app/components/Points/Points.tsx
- src/app/components/Points/StakerPoints.tsx
> fix small points amount display

- src/app/api/getFinalityProviders.ts
- src/app/components/Staking/FinalityProviders/FinalityProvider.tsx
- src/app/components/Staking/FinalityProviders/FinalityProviderSearch.tsx
- src/app/components/Staking/FinalityProviders/FinalityProviders.tsx
- src/app/hooks/api/useFinalityProviders.ts
- src/app/hooks/services/useFinalityProviderService.ts
- src/app/types/finalityProviders.ts
- tailwind.config.ts
- added new column (static UI)
- added support for server side sorting
- Implemented `FinalityProviderService`
> feat(phase-2): finality providers

- src/app/common/constants.ts
- src/app/components/Modals/FilterOrdinalsModal.tsx
Shows the filter ordinals modal only once. `dev` branch variant
> feature: Filter ordinals modal show once - dev

- src/app/common/constants.ts
- src/app/page.tsx
Shows the filter ordinals modal only once. `main` branch variant
> feature: Filter ordinals modal show once - main

- src/app/components/Connect/ConnectSmall.tsx
- src/app/components/Connect/ConnectedSmall.tsx
Before: https://i.imgur.com/EZlmiXH.png
After: https://i.imgur.com/Sf2zWAs.png
> feature: Ordinals included

- package-lock.json
- package.json
- src/app/components/Notification/DetailsButton.tsx
- src/app/components/Notification/FloatingTopBar.tsx
- src/app/components/Notification/IconWrapper.tsx
- src/app/components/Notification/Notification.tsx
- src/app/components/Notification/NotificationContainer.tsx
- src/app/components/Notification/NotificationText.tsx
- src/app/components/Notification/NotificationTitle.tsx
- src/app/globals.css
- src/app/hooks/useNotification.tsx
- src/app/page.tsx
- src/app/providers.tsx
- src/config/screen-breakpoints.ts
- tailwind.config.ts
Screenshot:
Let me know what do you think.
> add notification component

- src/app/api/getFinalityProviders.ts
- src/app/components/Staking/FinalityProviders/FinalityProvider.tsx
- src/app/types/finalityProviders.ts
updated the fp states and adopt v2 fp endpoints
> adopt fp endpoint

- src/app/api/getParams.ts
related PR: https://github.com/babylonlabs-io/staking-api-service/pull/105
> rename v2 global params

- src/app/components/Modals/EOIModal.tsx
- src/app/components/Modals/PendingVerificationModal.tsx
- src/app/components/Staking/Staking.tsx
- src/app/context/wallet/WalletConnectionProvider.tsx
- src/app/hooks/api/useDelegationV2.ts
- src/app/hooks/services/useTransactionService.tsx
- src/config/wallet/babylon.ts
Wires up EOI modal and Pending Verification modal to the actual data
Video: https://youtu.be/6oY0IG2ZIjI
Closes #315 and #316
Local storage is not a part of this tickets, so as tables call to actions from the buttons.
> Feature: EOI modal, Pending verification modal

- src/app/api/getSystemStats.ts
- src/app/components/Stats/Stats.tsx
- src/app/hooks/api/useSystemStats.ts
> integrate stats

- src/app/api/getParams.ts
- src/app/components/FAQ/FAQ.tsx
- src/app/components/Modals/PreviewModal.tsx
- src/app/components/Summary/Summary.tsx
- src/app/types/params.ts
> add confirmation depth

- src/app/components/Modals/PreviewModal.tsx
- src/app/components/Modals/UnbondModal.tsx
- src/app/components/Modals/WithdrawModal.tsx
- src/app/components/Staking/Staking.tsx
- src/app/hooks/useBreakpoint.ts
> UI preview modal

- package-lock.json
- package.json
- src/app/components/Delegations/Delegations.tsx
- src/app/components/Modals/ConfirmationModal.tsx
- src/app/components/Modals/PendingVerificationModal.tsx
- src/app/components/Modals/PreviewModal.tsx
- src/app/components/Modals/ResponsiveDialog.tsx
- src/app/components/Modals/SlashingModal.tsx
- src/app/components/Modals/StakeModal.tsx
- src/app/components/Modals/SubmitModal.tsx
- src/app/components/Modals/TransitionModal/StageStepping.tsx
- src/app/components/Modals/TransitionModal/Step.tsx
- src/app/components/Modals/UnbondErrorModal.tsx
- src/app/components/Modals/UnbondModal.tsx
- src/app/components/Modals/WithdrawModal.tsx
- src/app/components/Staking/Staking.tsx
- src/app/hooks/services/useDelegationService.ts
- src/app/hooks/storage/useDelegationStorage.ts
- src/app/state/DelegationV2State.tsx
- src/components/delegations/DelegationList/components/ActionButton.tsx
- src/components/delegations/DelegationList/components/DelegationModal.tsx
- src/components/delegations/DelegationList/components/Inception.tsx
- src/components/delegations/DelegationList/index.tsx
> feat: hook up modals

- next.config.mjs
- package-lock.json
- package.json
Adds Leap hostname so that their injectable wallet can properly show an icon
> feature: Leap hostname - injectable wallet icon

- package.json
- src/app/components/FAQ/data/questions.ts
- src/app/components/Modals/ConnectModal.tsx
Changes the text in the:
1. Connection modal https://i.imgur.com/eNqY4cy.png
2. FAQ https://i.imgur.com/s3LMcEM.png
@jrwbabylonlab @vitsalis if this is not needed - can be closed
> feat: HW wallets OneKey Pro

- package-lock.json
> revert package-lock.json committed from 055c143

- src/app/components/Staking/Staking.tsx
> update staking form to use fp state

- package-lock.json
- package.json
Fixes Keystone signing messages psbts
> chore: Bump wallet connect

- src/app/components/Staking/Staking.tsx
- src/utils/isStakingSignReady.ts
currently its added in the old staking.tsx, this needs to be handled in the refactored staking form as well @totraev
> 403 blocking staking if no bbn balance

- src/app/components/Delegations/Delegation.tsx
- src/app/constants.ts
- src/app/state/FinalityProviderState.tsx
- src/components/common/Hint/index.tsx
- src/components/delegations/DelegationList/components/FinalityProviderMoniker.tsx
- src/components/delegations/DelegationList/components/Status.tsx
- src/components/delegations/DelegationList/index.tsx
- tsconfig.json
> 528 UI show delegation with slashed design

- src/app/components/Stats/Stats.tsx
> chore: update FP in stats section text

- package-lock.json
- src/app/components/Hash/Hash.tsx
- src/app/components/Staking/FinalityProviders/FinalityProviderColumns.tsx
- src/app/components/Staking/FinalityProviders/FinalityProviderTable.tsx
- src/app/state/FinalityProviderState.tsx
table added controlled states and deselect should work as expected.
> fix fp deselect error

- src/config/network/bbn/devnet.ts
- src/config/network/bbn/testnet.ts
> feat: BABY coin

- src/app/components/Delegations/Delegation.tsx
- src/app/components/Delegations/DelegationActions.tsx
- src/app/components/Modals/ErrorModal.tsx
> show unbond only if fp is slashed

- src/app/state/FinalityProviderState.tsx
> default sort desc by active amount

- src/app/components/Delegations/DelegationActions.tsx
this PR:
- disabled the register button when insufficient chain balance
> disable register message and include insufficient balance message

- src/app/components/PersonalBalance/PersonalBalance.tsx
- src/app/state/index.tsx
closes #575 
Tooltip design has been updated on figma, we should do in in another ticket @totraev
> add amount tooltip

- next.config.mjs
- src/middleware.ts
- tests/middleware.test.ts
> fix rsc header vulnerability

- package-lock.json
- package.json
- src/app/constants.ts
- src/app/hooks/services/useDelegationService.ts
- src/app/types/network.ts
- src/config/network/bbn.ts
- src/config/network/bbn/canary.ts
- src/config/network/btc.ts
- tests/config/index.test.ts
- tests/utils/local_storage/calculateDelegationsDiff.test.ts
- tests/utils/local_storage/filterDelegationsLocalStorage.test.ts
added `canary` network
https://github.com/babylonlabs-io/bbn-wallet-connect/pull/222
> add network config

- src/app/state/FinalityProviderState.tsx
> fix slashed fp tooltip

- package-lock.json
- package.json
Bumps Tomo wallet connector to the latest version
> feat: Bump Tomo wallet connector

- package-lock.json
- package.json
> fix: initEccLib issue

- src/app/context/tomo/BTCConnector.tsx
- src/app/context/wallet/BTCWalletProvider.tsx
- src/app/hooks/client/api/useOrdinals.ts
> fix: fallback for getInscriptions method

- src/app/components/ThemeToggle/ThemeToggle.tsx
- src/app/components/Wallet/Connect.tsx
fix weird default toggle behavior on include inscriptions
> fix default toggle

- src/app/state/StakingState.tsx
- src/components/staking/FeeModal/components/CustomLabel.tsx
- src/components/staking/FeeModal/components/Label.tsx
- src/components/staking/FeeModal/components/WarningTooltip.tsx
- src/components/staking/FeeModal/index.tsx
- src/components/staking/StakingForm/components/BTCFeeRate.tsx
- src/utils/getFeeRateFromMempool.ts
> fix: display inclusion warning instead of error

- src/app/api/getDelegationsV2.ts
- src/app/components/Wallet/Connect.tsx
- src/app/hooks/client/api/useDelegationsV2.ts
- src/app/state/DelegationV2State.tsx
> feat: BTC PK + Babylon Address

- src/app/components/PersonalBalance/PersonalBalance.tsx
- src/app/state/BalanceState.tsx
- src/app/state/DelegationV2State.tsx
> feat: staked balance

- package-lock.json
- package.json
- src/app/components/NetworkBadge/NetworkBadge.tsx
- src/app/types/network.ts
- src/config/index.ts
- src/config/network/bbn.ts
- src/config/network/btc.ts
- src/utils/wallet/index.ts
Don't merge before https://github.com/babylonlabs-io/simple-staking/pull/727
> fix: remove canary network

- src/config/network/bbn/testnet.ts
Testnet RPC and LCD to use Babylon values
> feat: Testnet use Babylon RPC LCD

- .env.example
- README.md
- src/config/network/bbn/canary.ts
- src/config/network/bbn/devnet.ts
- src/config/network/bbn/testnet.ts
Adds a support fo env variable to override the default RPC LCD values
> feat: RPC LCD env support

- src/app/api/apiWrapper.ts
- src/app/api/postFilterOrdinals.ts
- src/app/api/verifyBTCAddress.ts
- src/app/components/Modals/ErrorModal.tsx
- src/app/constants/errorMessages.ts
- src/app/context/Error/ErrorProvider.tsx
- src/app/context/Error/errors/clientError.ts
- src/app/context/Error/errors/serverError.ts
- src/app/hooks/client/api/useOrdinals.ts
- src/app/types/errors.ts
- tests/app/api/apiWrapper.test.ts
> improve error handling

- .eslintignore
- .husky/pre-commit
https://github.com/babylonlabs-io/simple-staking/issues/788
> fix: husky config to only commit staged files

- src/app/components/Delegations/DelegationActions.tsx
> fix unbond button style

- src/app/constants.ts
- src/app/constants/errorMessages.ts
- src/app/context/api/StakingStatsProvider.tsx
- src/app/context/rpc/BbnRpcProvider.tsx
- src/app/hooks/client/api/useDelegations.ts
- src/app/hooks/client/api/useDelegationsV2.ts
- src/app/hooks/client/api/useFinalityProviders.ts
- src/app/hooks/client/api/useFinalityProvidersV2.ts
- src/app/hooks/client/api/useNetworkFees.ts
- src/app/hooks/client/rpc/queries/useBbnQuery.ts
- src/app/hooks/client/rpc/useRpcErrorHandler.ts
- src/app/hooks/client/useClient.ts
- src/app/state/BalanceState.tsx
https://github.com/babylonlabs-io/simple-staking/issues/774
> feat: add RPC error on failure

- src/app/components/Modals/Phase2Here.tsx
https://github.com/babylonlabs-io/simple-staking/issues/800
https://github.com/babylonlabs-io/simple-staking/issues/817
> feat: updates blog post for offical launch

- src/app/components/Delegations/Delegation.tsx
- src/app/components/Delegations/DelegationActions.tsx
- src/app/state/FinalityProviderState.tsx
- src/app/types/delegations.ts
- src/components/staking/StakingModal/index.tsx
- src/utils/getState.ts
https://github.com/user-attachments/assets/3a4ce36e-09ea-4159-8934-a4fb78c54a4f
https://github.com/babylonlabs-io/simple-staking/issues/845
> feat: set up tooltip for unregistered finality provider

- src/components/staking/StakingForm/index.tsx
> feat: update copy for unavailable staking

- src/app/components/Staking/FinalityProviders/FinalityProviderFilter.tsx
- src/app/state/FinalityProviderState.tsx
- src/config/index.ts
Defaults the selector for the FP Filter list to Inactive
> feat: defaults FP filter to inactive

- src/components/delegations/DelegationList/NoDelegations.tsx
- src/components/delegations/DelegationList/index.tsx
> feat: change copy on NoDelegations message

- package-lock.json
- package.json
Bumps Babylon wallet connector, which bumps Tomo wallet connector
Tomo connector updated version: https://github.com/UnyxTech/tomo-wallet-provider/releases/tag/v1.1.15
- Features
-  The WalletProvider has added an init method to support wallets requiring asynchronous initializat
ion
- Bug fixes
-  fixed the namespace conflict issue with Keplr's Cosmos
-  updated the prompt message for Keystone BTC connection.
> feat: Bump wallet connector

- src/app/components/Stats/StatItem.tsx
> update tooltip mobile

- .github/workflows/ci.yml
Adds a GH workflow that runs the unit tests
> feat: add workflow for unit tests

- src/app/components/FAQ/data/questions.tsx
https://babylonlabs.atlassian.net/wiki/spaces/BABYLON/pages/95846447/Phase-2+FAQs
https://github.com/babylonlabs-io/simple-staking/issues/459
> feat: updates FAQ with new copy

- src/app/context/Error/errors/clientError.ts
- src/app/types/errors.ts
- src/errors/clientError.ts
- src/errors/codes.ts
closes #943 
Consolidated specific error codes into broader categories for simpler grouping and reporting, also refined comments for clarity
> define clientError Class

- package-lock.json
- package.json
- sentry.client.config.ts
- src/app/context/wallet/BTCWalletProvider.tsx
- src/app/context/wallet/CosmosWalletProvider.tsx
- src/hooks/useLogger.ts
This PR ensures proper unique user counting in Sentry
closes #870
> fix user count not tracked

- src/app/api/getSystemStats.ts
- src/app/components/Delegations/Delegations.tsx
- src/app/context/Error/ErrorProvider.tsx
- src/app/context/Error/errors/serverError.ts
- src/app/context/api/StakingStatsProvider.tsx
- src/app/context/wallet/BTCWalletProvider.tsx
- src/app/context/wallet/CosmosWalletProvider.tsx
- src/app/context/wallet/WalletConnectionProvider.tsx
- src/app/hooks/client/api/useDelegations.ts
- src/app/hooks/client/api/useDelegationsV2.ts
- src/app/hooks/client/api/useOrdinals.ts
- src/app/hooks/client/rpc/mutation/useSigningStargateClient.ts
- src/app/hooks/client/rpc/queries/useBbnQuery.ts
- src/app/hooks/client/rpc/useRpcErrorHandler.ts
- src/app/hooks/client/useClient.ts
- src/app/hooks/services/useDelegationService.ts
- src/app/hooks/services/useRegistrationService.ts
- src/app/hooks/services/useStakingManagerService.ts
- src/app/hooks/services/useStakingService.ts
- src/app/hooks/services/useTransactionService.ts
- src/app/hooks/services/useV1TransactionService.ts
- src/app/hooks/useHealthCheck.ts
- src/app/state/FinalityProviderState.tsx
- src/hooks/useLogger.ts
- src/utils/getPrices.ts
- src/utils/local_storage/filterDelegationsLocalStorage.ts
- src/utils/mempool_api.ts
- tests/utils/local_storage/filterDelegationsLocalStorage.test.ts
- tests/utils/mempool/getFundingUTXOs.test.ts
- additional info logs
- additional geoblocked info in info logs
- remove unused legacy error code
> fix: add debug logs

- src/utils/FeatureFlagService.ts
Applies the following:
https://babylonlabs.atlassian.net/wiki/spaces/BABYLON/pages/182256254/Web+Feature+Flag+guideline
> feat: add FeatureFlag service (multistaking)

- src/app/components/Modals/MultistakingModal/MultistakingStartModal.tsx
> feat: add multistakingStartModal

- src/app/components/Multistaking/FinalityProviderModal/FinalityProviderModal.tsx
https://github.com/babylonlabs-io/simple-staking/issues/996
> feat: adds Finality Provider selection modal

- package-lock.json
- package.json
Removes unused library `@bitcoinerlab/secp256k1`
> feat: Remove unused secp256k1

- src/app/components/Multistaking/FinalityProviderModal/FinalityProviderItem.tsx
- src/app/components/Multistaking/MultistakingForm/BTCFeeRate.tsx
- src/app/components/Multistaking/MultistakingForm/FeesSection.tsx
- src/app/components/Multistaking/MultistakingForm/MultistakingForm.tsx
- src/app/components/Multistaking/MultistakingForm/PreviewButton.tsx
- src/components/staking/StakingForm/components/BTCFeeRate.tsx
https://github.com/user-attachments/assets/fbf7660e-bc89-40d9-ad2e-8acd182adeca
> fix: invalid form values on load, fix finality provider not updating when removed, improve text on CTA

- src/app/components/Multistaking/FinalityProviderModal/FinalityProviderItem.tsx
- src/app/components/Multistaking/MultistakingForm/AmountSubsection.tsx
- src/app/components/Multistaking/MultistakingForm/MultistakingForm.tsx
> fix: copy changes, remove BSN icon

- .github/workflows/publish.yaml
- src/app/config/network/bbn/canary.ts
Also, remove stale deployment environments.
> chore: Rename private-mainnet to staging

- src/app/state/StakingState.tsx
- tests/app/state/StakingState.test.tsx
> fix: geoblocked message

- src/app/components/Alerts/Alert.tsx
- src/app/components/Multistaking/MultistakingForm/FormAlert.tsx
- src/app/components/Multistaking/MultistakingForm/MultistakingForm.tsx
- src/app/components/Multistaking/MultistakingForm/PreviewButton.tsx
- src/app/context/wallet/BTCWalletProvider.tsx
- src/app/context/wallet/CosmosWalletProvider.tsx
alerts are shown on geoblocked and `staking_disabled`
> feat: alert on multistaking form for geoblock and disabled_staking flag

- src/app/components/Multistaking/MultistakingForm/MultistakingForm.tsx
- src/app/components/Multistaking/MultistakingForm/PreviewButton.tsx
- src/app/state/MultistakingState.tsx
- src/app/state/StakingState.tsx
- src/app/utils/formTransforms.ts
> feat: implement dynamic CTA button colors for different error states

- src/ui/components/Multistaking/FinalityProviderField/FinalityProviderField.tsx
- src/ui/components/Multistaking/FinalityProviderField/FinalityProviderItem.tsx
- src/ui/components/Multistaking/FinalityProviderField/FinalityProviderModal.tsx
- src/ui/components/Multistaking/FinalityProviderField/FinalityProviders.tsx
- src/ui/components/Multistaking/MultistakingForm/MultistakingForm.tsx
- src/ui/components/Staking/FinalityProviders/FinalityProviderTable.tsx
- src/ui/components/Staking/FinalityProviders/FinalityProviders.tsx
- src/ui/state/MultistakingState.tsx
- src/ui/state/StakingState.tsx
Note: as soon as 2.5 UI doesn't support dynamic term value we should set `NEXT_PUBLIC_FIXED_STAKING_TERM=true` on `devnet`
> fix: multistaking form

- src/ui/components/Multistaking/MultistakingForm/AmountBalanceInfo.tsx
> fix: disable max button

- src/ui/hooks/client/api/useOrdinals.ts
If ordinals checking fail for some reason - show an error modal properly, log it, and make application work without ordinals
> fix: ordinals empty array

- package-lock.json
- package.json
- src/ui/components/Delegations/DelegationList/components/DelegationModal.tsx
- src/ui/components/Delegations/DelegationList/index.tsx
- src/ui/components/Delegations/Delegations.tsx
- src/ui/components/Modals/SignDetailsModal.tsx
- src/ui/components/Modals/SignModal/SignModal.tsx
- src/ui/components/Modals/SignModal/Step.tsx
- src/ui/components/SignDetails/SignDetails.tsx
- src/ui/components/Staking/StakingModal/index.tsx
- src/ui/hooks/services/useDelegationService.ts
- src/ui/state/DelegationState.tsx
- src/ui/state/DelegationV2State.tsx
- src/ui/state/StakingState.tsx
Adds the UI for showing the data when user calls `.signPsbt`
Closes #929
> feat: No blind signing UI

- package-lock.json
- package.json
> fix: bump wallet connector

- src/ui/common/components/Modals/PreviewModal.tsx
- src/ui/common/components/Modals/PreviewMultistakingModal.tsx
- src/ui/common/components/Multistaking/MultistakingForm/AmountBalanceInfo.tsx
- src/ui/common/components/Multistaking/MultistakingModal/MultistakingModal.tsx
- src/ui/common/components/Staking/DelegationForm/components/BBNFeeAmount.tsx
- src/ui/common/components/Staking/DelegationForm/components/BTCFeeAmount.tsx
- src/ui/common/components/Staking/DelegationForm/components/Total.tsx
- src/ui/common/config/network/bbn.ts
- src/ui/common/config/network/btc.ts
- src/ui/common/utils/formatBTCTvl.ts
hide USD display on no usd value network
> fix: hide USD value

- src/ui/common/components/Activity/Activity.tsx
- src/ui/common/components/Activity/components/ActivityList.tsx
- src/ui/common/components/ActivityCard/ActivityCard.tsx
- src/ui/common/components/ActivityCard/components/ActivityCardActionSection.tsx
- src/ui/common/components/ActivityCard/components/ActivityCardAmountSection.tsx
- src/ui/common/components/ActivityCard/components/ActivityCardDetailsSection.tsx
- src/ui/common/components/ActivityCard/components/ActivityListItem.tsx
- src/ui/common/components/ActivityCard/index.tsx
- src/ui/common/components/Delegations/DelegationList/components/Status.tsx
- src/ui/common/components/Hash/Hash.tsx
- src/ui/common/page.tsx
> add activity card

- src/ui/common/components/Multistaking/MultistakingForm/SubmitButton.tsx
- src/ui/legacy/components/Multistaking/MultistakingForm/SubmitButton.tsx
> fix: button clarity and visual hierarchy

- src/ui/common/state/StakingExpansionState.tsx
- uses `delegation:expand` to show steps after the preview
Closes https://github.com/babylonlabs-io/simple-staking/issues/1387
> fix: staking expansion step bus listener

- src/ui/baby/components/ActivityList/index.tsx
- src/ui/baby/hooks/services/useDelegationService.ts
- src/ui/baby/state/DelegationState.tsx
- src/ui/common/utils/time.ts
This allows us to:
- Optimistically set the unbonding state
- Poll to get latest status of the unbonding
- Display a "processing" status for the user
> feat: implements unbonding states

- src/ui/baby/components/UnbondingModal/index.tsx
- src/ui/baby/state/StakingState.tsx
- src/ui/baby/validation/unbondingValidation.ts
- src/ui/common/utils/bbn.ts
> feat: adds validation to baby unbonding modal

- src/ui/common/hooks/services/useExpansionHistoryService.ts
- improves caching for staking expansion
Closes https://github.com/babylonlabs-io/simple-staking/issues/1348
> feat: expansion improve caching

- src/ui/common/components/Activity/components/NonExpandableExpansion.tsx
- src/ui/common/components/ActivityCard/ActivityCard.tsx
- src/ui/common/components/ActivityCard/components/ActivityCardDetailsSection.tsx
- src/ui/common/components/Multistaking/MultistakingForm/UnavailableWarning.tsx
- src/ui/common/constants.ts
> feat: non expandable expansion

- src/ui/baby/components/AmountField/index.tsx
- src/ui/baby/layout.tsx
- src/ui/common/components/ActivityCard/utils/activityCardTransformers.tsx
- src/ui/common/components/FAQ/FAQ.tsx
- src/ui/common/components/FAQ/data/questions.tsx
- src/ui/common/components/Menu/WalletMenu/components/WalletInfoSection.tsx
- src/ui/common/components/Multistaking/MultistakingForm/AmountSection.tsx
- src/ui/common/page.tsx
- src/ui/common/utils/time.ts
- tests/utils/formatTime.test.ts
- tests/utils/time.test.ts
- add baby faq section and change link colors, resolves #1453
before:
after:
- disable autofocus on amount field, resolves #1458
- add option to show time without precision in activity card, resolves #1457
before:
after:
- use correct btc icon depending on the configuration, resolves #1455
> fix: ui bug fixes

- src/ui/common/components/Activity/components/StakeExpansionSection.tsx
- src/ui/common/components/StakingExpansion/StakingExpansionModal.tsx
- src/ui/common/hooks/services/useStakingExpansionService.ts
- src/ui/common/hooks/services/useTransactionService.ts
- this PR does not allow to work with staking expansion until the `UTXOs` are fully loaded
- `UI` layer protection
- `Modal` layer protection
- `Service` layer protection
Closes: https://github.com/babylonlabs-io/simple-staking/issues/1471
> fix: expansion - utxo usage

- src/ui/common/components/StakingExpansion/VerifiedStakeExpansionModal.tsx
- src/ui/common/constants.ts
- adds a type for `expansion` operations
Closes https://github.com/babylonlabs-io/simple-staking/issues/1479
> feat: expansion operations

- src/ui/common/components/Stats/Stats.tsx
> fix: show apr as 0% when not mainnet

- src/ui/baby/components/ValidatorTable/columns.tsx
- src/ui/baby/components/ValidatorTable/index.tsx
Also made the `ResponsiveDialog` wider to fit new column. (same size as `ExpansionChainSelectionModal`, `FinalityProviderModal`, `ChainSelectionModal`)
> feat: show total stake of validator in validator selection

- src/ui/common/providers.tsx
require merging https://github.com/babylonlabs-io/babylon-toolkit/pull/84
> feat: integrate CoreUIProvider and enhance portal management in Provider
